version: "3"
services:
  caddy:
    image: "abiosoft/caddy:no-stats"
    # environment:

    links:
      - server
    # external_links:
    #   - tob_tob-api_1:tob-api
    networks:
      - pa
    ports:
      - ${WEB_HTTP_PORT:-7000}:80
      - ${WEB_HTTPS_PORT:-7443}:443
    volumes:
      - ../caddy/Caddyfile:/etc/Caddyfile

  server:
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    environment:
      - LEDGER_URL=${LEDGER_URL}
      - LEDGER_PROTOCOL_VERSION=${LEDGER_PROTOCOL_VERSION}
      - GENESIS_URL=${GENESIS_URL}
    volumes:
      - ../server:/app
    networks:
      - pa
    # ports:
    #   - 7000:7000
    # command: hupper -m server
    command: hupper -m server

  app:
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    # environment:
    #   - PORT=7000
    volumes:
      - ../app:/app
      - /app/node_modules
    networks:
      - pa
    ports:
      - 7100:7100
    command: ionic serve --port 7100

networks:
  ? pa
