version: "3"
services:
  server:
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    environment:
      - LEDGER_URL=${LEDGER_URL}
      - LEDGER_PROTOCOL_VERSION=${LEDGER_PROTOCOL_VERSION}
      - GENESIS_URL=${GENESIS_URL}
    volumes:
      - ../server:/app
    networks:
      - tob
    ports:
      - 7000:7000
    # command: hupper -m server
    command: hupper -m server

  app:
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    # environment:
    #   - PORT=7000
    volumes:
      - ../app:/app
      - /app/node_modules
    networks:
      - tob
    ports:
      - 7100:7100
    command: ionic serve --port 7100

networks:
  ? tob
